# Generated by ariadne-codegen
# Source: queries

from typing import Any, Optional, Union

from .base_client import BaseClient
from .base_model import UNSET, UnsetType
from .find_book_by_isbn import FindBookByIsbn
from .find_books_by_ids import FindBooksByIds
from .search_books import SearchBooks
from .verify_token import VerifyToken


def gql(q: str) -> str:
    return q


class HardcoverClient(BaseClient):
    def find_book_by_isbn(self, isbn: str, **kwargs: Any) -> FindBookByIsbn:
        query = gql("""
            query FindBookByIsbn($isbn: String!) {
              books(
                where: {editions: {_or: [{isbn_13: {_eq: $isbn}}, {isbn_10: {_eq: $isbn}}]}}
                limit: 5
              ) {
                ...BookFields
                editions(
                  where: {_or: [{isbn_13: {_eq: $isbn}}, {isbn_10: {_eq: $isbn}}]}
                  order_by: {users_count: desc_nulls_last}
                  limit: 5
                ) {
                  ...EditionFields
                }
              }
            }

            fragment BookFields on books {
              id
              title
              slug
              contributions(limit: 20) {
                contribution
                author {
                  name
                }
              }
              book_series(limit: 10) {
                position
                featured
                series {
                  name
                }
              }
              image {
                url
              }
            }

            fragment EditionFields on editions {
              id
              title
              isbn_10
              isbn_13
              release_date
              users_count
              reading_format_id
              publisher {
                name
              }
              language {
                code3
              }
              image {
                url
              }
            }
            """)
        variables: dict[str, object] = {"isbn": isbn}
        response = self.execute(
            query=query, operation_name="FindBookByIsbn", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return FindBookByIsbn.model_validate(data)

    def find_books_by_ids(
        self,
        ids: Union[Optional[list[int]], UnsetType] = UNSET,
        languages: Union[Optional[list[str]], UnsetType] = UNSET,
        **kwargs: Any,
    ) -> FindBooksByIds:
        query = gql("""
            query FindBooksByIds($ids: [Int!], $languages: [String!]) {
              books(where: {id: {_in: $ids}}, order_by: {users_read_count: desc_nulls_last}) {
                ...BookFields
                editions(
                  where: {reading_format_id: {_in: [1, 4]}, language: {_or: [{code3: {_in: $languages}}, {code3: {_is_null: true}}]}}
                  order_by: {users_count: desc_nulls_last}
                  limit: 25
                ) {
                  ...EditionFields
                }
              }
            }

            fragment BookFields on books {
              id
              title
              slug
              contributions(limit: 20) {
                contribution
                author {
                  name
                }
              }
              book_series(limit: 10) {
                position
                featured
                series {
                  name
                }
              }
              image {
                url
              }
            }

            fragment EditionFields on editions {
              id
              title
              isbn_10
              isbn_13
              release_date
              users_count
              reading_format_id
              publisher {
                name
              }
              language {
                code3
              }
              image {
                url
              }
            }
            """)
        variables: dict[str, object] = {"ids": ids, "languages": languages}
        response = self.execute(
            query=query, operation_name="FindBooksByIds", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return FindBooksByIds.model_validate(data)

    def search_books(self, query: str, **kwargs: Any) -> SearchBooks:
        _query = gql("""
            query SearchBooks($query: String!) {
              search(query: $query, query_type: "Book", per_page: 25) {
                ids
              }
            }
            """)
        variables: dict[str, object] = {"query": query}
        response = self.execute(
            query=_query, operation_name="SearchBooks", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return SearchBooks.model_validate(data)

    def verify_token(self, **kwargs: Any) -> VerifyToken:
        query = gql("""
            query VerifyToken {
              me {
                id
              }
            }
            """)
        variables: dict[str, object] = {}
        response = self.execute(
            query=query, operation_name="VerifyToken", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return VerifyToken.model_validate(data)
