# Generated by ariadne-codegen
# Source: queries

from .base_model import BaseModel
from .fragments import BookFields, EditionFields


class FindBookByIsbn(BaseModel):
    books: list["FindBookByIsbnBooks"]


class FindBookByIsbnBooks(BookFields):
    editions: list["FindBookByIsbnBooksEditions"]


class FindBookByIsbnBooksEditions(EditionFields):
    pass


FindBookByIsbn.model_rebuild()
FindBookByIsbnBooks.model_rebuild()
