# Generated by ariadne-codegen
# Source: queries

from .base_model import BaseModel
from .fragments import BookFields, EditionFields


class FindBooksByIds(BaseModel):
    books: list["FindBooksByIdsBooks"]


class FindBooksByIdsBooks(BookFields):
    editions: list["FindBooksByIdsBooksEditions"]


class FindBooksByIdsBooksEditions(EditionFields):
    pass


FindBooksByIds.model_rebuild()
FindBooksByIdsBooks.model_rebuild()
