# Generated by ariadne-codegen
# Source: queries

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class BookFields(BaseModel):
    id: int
    title: Optional[str]
    slug: Optional[str]
    contributions: list["BookFieldsContributions"]
    book_series: list["BookFieldsBookSeries"]
    image: Optional["BookFieldsImage"]


class BookFieldsContributions(BaseModel):
    contribution: Optional[str]
    author: Optional["BookFieldsContributionsAuthor"]


class BookFieldsContributionsAuthor(BaseModel):
    name: str


class BookFieldsBookSeries(BaseModel):
    position: Optional[float]
    featured: bool
    series: Optional["BookFieldsBookSeriesSeries"]


class BookFieldsBookSeriesSeries(BaseModel):
    name: str


class BookFieldsImage(BaseModel):
    url: Optional[str]


class EditionFields(BaseModel):
    id: int
    title: Optional[str]
    isbn_10: Optional[str]
    isbn_13: Optional[str]
    release_date: Optional[str]
    users_count: int
    reading_format_id: int
    publisher: Optional["EditionFieldsPublisher"]
    language: Optional["EditionFieldsLanguage"]
    image: Optional["EditionFieldsImage"]


class EditionFieldsPublisher(BaseModel):
    name: Optional[str]


class EditionFieldsLanguage(BaseModel):
    code_3: Optional[str] = Field(alias="code3")


class EditionFieldsImage(BaseModel):
    url: Optional[str]


BookFields.model_rebuild()
EditionFields.model_rebuild()
