# Generated by ariadne-codegen
# Source: queries

from typing import Optional

from .base_model import BaseModel


class SearchBooks(BaseModel):
    search: Optional["SearchBooksSearch"]


class SearchBooksSearch(BaseModel):
    ids: Optional[list[Optional[int]]]


SearchBooks.model_rebuild()
