# Generated by ariadne-codegen
# Source: queries

from .base_model import BaseModel


class VerifyToken(BaseModel):
    me: list["VerifyTokenMe"]


class VerifyTokenMe(BaseModel):
    id: int


VerifyToken.model_rebuild()
